### ISSUE TITLE
Strange output with my VRM

### ISSUE THREAD

**Issue by from2001** [segurvita/PolySpatialEnvironmentDiffuseShader#1]
Hi Segur,
Thank you for the great shader.

I tried the shader with my VRM model, the output looks strange.
Please take a look. My VRM is [this](https://styly.inc/wp-content/uploads/VRMs/STYLY-Chan-A.vrm).

<img width="1074" alt="Screenshot 2024-05-06 at 16 39 05" src="https://github.com/segurvita/PolySpatialEnvironmentDiffuseShader/assets/387880/ac18d46d-f733-420c-aaf7-0e5930f71ce6">

**Comment by from2001** [comment]
I found that the materials with the parameter Double Sided=Off for MToon10 shader became black.

<img width="1819" alt="Screenshot 2024-05-06 at 16 59 21" src="https://github.com/segurvita/PolySpatialEnvironmentDiffuseShader/assets/387880/c3562c31-e77f-4ffd-a819-8d1370ae297c">

**Comment by segurvita** [comment]
Hi @from2001,
Thank you for trying out this shader right away.

As you mentioned, this shader currently does not support `Double Sided` yet.

I'll have this supported soon, so please wait a little longer.

**Comment by from2001** [comment]
Hi @segurvita 

Great. I look forward to it.

When it's done, I'll replace my material generator with yours.

**Comment by segurvita** [comment]
I inform you that I have fixed the bugs related to transparency and culling.

**Comment by from2001** [comment]
Thank you for the improvement, but there is still strange part.

It looks OK in Scene view, but there are some black part in GameView.
<img width="1991" alt="Screenshot 2024-05-07 at 1 22 12" src="https://github.com/segurvita/PolySpatialEnvironmentDiffuseShader/assets/387880/67a72c7b-338b-4e76-87ad-888fff4fc463">

**Comment by segurvita** [comment]
Thank you for letting me know.
I'll check again.

**Comment by segurvita** [comment]
I have just fixed the Transparent and AlphaClipping bugs.
I have confirmed that the VRM file you provided is rendered somewhat naturally on the actual AppleVisionPro device.
Therefore, I closed this Issue.

However, I know that DoubleSided (Culling) still does not render correctly on the actual AppleVisionPro device.
In order to fix this issue, the implementation of the Shader needs to be fundamentally reviewed, and it is difficult to resolve this issue immediately, so I have created another Issue (#6).
